language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
sudo: false
cache: bundler
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
env:
  matrix:
    - SOLIDUS_BRANCH=v1.1 DB=postgres
    - SOLIDUS_BRANCH=v1.2 DB=postgres
    - SOLIDUS_BRANCH=v1.3 DB=postgres
    - SOLIDUS_BRANCH=v1.4 DB=postgres
    - SOLIDUS_BRANCH=v2.0 DB=postgres
    - SOLIDUS_BRANCH=v2.1 DB=postgres
    - SOLIDUS_BRANCH=master DB=postgres
    - SOLIDUS_BRANCH=v1.1 DB=mysql
    - SOLIDUS_BRANCH=v1.2 DB=mysql
    - SOLIDUS_BRANCH=v1.3 DB=mysql
    - SOLIDUS_BRANCH=v1.4 DB=mysql
    - SOLIDUS_BRANCH=v2.0 DB=mysql
    - SOLIDUS_BRANCH=v2.1 DB=mysql
    - SOLIDUS_BRANCH=master DB=mysql